INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Unspecified', '000000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control', '110000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Broadcast Transmitter Antennae', '110100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Civil Affairs', '110200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Civil-Military Cooperation', '110300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Information Operations', '110400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Liaison', '110500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Military Information Support (MISO)', '110600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Military Information Support (MISO) : Broadcast Transmitter Antennae', '110601', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Radio', '110700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Radio Relay', '110800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Radio Teletype Center', '110900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Signal', '111000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Signal : Radio', '111001', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Signal : Radio Relay', '111002', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Signal : Teletype', '111003', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Signal : Tactical Satellite', '111004', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Signal : Video Imagery (Combat Camera)', '111005', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Tactical Satellite', '111100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Command and Control : Video Imagery (Combat Camera)', '111200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Air Assault with Organic Lift', '120100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Air Traffic Services/Airfield Operations', '120200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Amphibious', '120300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Antitank/Antiarmor', '120400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Antitank/Antiarmor : Armored', '120401', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Antitank/Antiarmor : Motorized', '120402', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Armor/Armored/Mechanized/Self-Propelled/Tracked', '120500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Armor/Armored/Mechanized/Self-Propelled/Tracked : Reconnaissance/Cavalry/Scout', '120501', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Armor/Armored/Mechanized/Self-Propelled/Tracked : Amphibious', '120502', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Army Aviation/Aviation Rotary Wing', '120600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Army Aviation/Aviation Rotary Wing : Reconnaissance', '120601', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Aviation Composite', '120700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Aviation Fixed Wing', '120800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Aviation Fixed Wing : Reconnaissance', '120801', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Combat', '120900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Combined Arms', '121000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Infantry', '121100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Infantry : Amphibious', '121101', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Infantry : Armored/Mechanized/Tracked', '121102', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Infantry : Main Gun System', '121103', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Infantry : Motorized', '121104', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Infantry : Infantry Fighting Vehicle', '121105', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Observer', '121200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Reconnaissance/Cavalry/Scout', '121300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Reconnaissance/Cavalry/Scout : Reconnaissance and Surveillance', '121301', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Reconnaissance/Cavalry/Scout : Marine', '121302', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Reconnaissance/Cavalry/Scout : Motorized', '121303', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Sea Air Land (SEAL)', '121400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Sniper', '121500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Surveillance', '121600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Special Forces', '121700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : SOF', '121800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : SOF : Fixed Wing MISO', '121801', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : SOF : Ground', '121802', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : SOF : Special Boat', '121803', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : SOF : Special SSNR', '121804', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : SOF : Underwater Demolition Team', '121805', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Movement and Maneuver : Unmanned Aerial Systems', '121900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Air Defense', '130100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Air Defense : Main Gun System', '130101', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Air Defense : Missile', '130102', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Air/Land Naval Gunfire Liaison', '130200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Field Artillery', '130300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Field Artillery : Self-propelled', '130301', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Field Artillery : Target Acquisition', '130302', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Field Artillery Observer', '130400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Joint Fire Support', '130500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Meteorological', '130600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Missile', '130700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Mortar', '130800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Mortar : Armored/Mechanized/Tracked', '130801', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Mortar : Self-Propelled Wheeled', '130802', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Mortar : Towed', '130803', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Fires : Survey', '130900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : CBRN Defense', '140100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : CBRN Defense : Mechanized', '140101', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : CBRN Defense : Motorized', '140102', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : CBRN Defense : Reconnaissance', '140103', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : CBRN Defense : Reconnaissance Armored', '140104', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : CBRN Defense : Reconnaissance Equipped', '140105', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Combat Support (Maneuver Enhancement)', '140200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Criminal Investigation Division', '140300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Diving', '140400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Dog', '140500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Drilling', '140600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Engineer', '140700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Engineer : Mechanized', '140701', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Engineer : Motorized', '140702', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Engineer : Reconnaissance', '140703', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Explosive Ordnance Disposal (EOD)', '140800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Field Camp Construction', '140900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Fire Fighting/Fire Protection', '141000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Geospatial Support/Geospatial Information Support', '141100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Military Police', '141200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Mine', '141300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Mine Clearing', '141400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Mine Launching', '141500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Mine Laying', '141600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Security', '141700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Security : Mechanized', '141701', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Security : Motorized', '141702', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Search and Rescue', '141800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Security Police (Air)', '141900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Shore Patrol', '142000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Protection : Topographic', '142100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Analysis', '150100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Counterintelligence', '150200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Direction Finding', '150300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Electronic Ranging', '150400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Electronic Warfare', '150500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Electronic Warfare : Analysis', '150501', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Electronic Warfare : Direction Finding', '150502', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Electronic Warfare : Intercept', '150503', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Electronic Warfare : Jamming', '150504', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Electronic Warfare : Search', '150505', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Intercept (Search and Recording)', '150600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Interrogation', '150700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Jamming', '150800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Joint Intelligence Center', '150900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Military Intelligence', '151000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Search', '151100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Intelligence : Sensor', '151200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment', '160000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Administrative', '160100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : All Classes of Supply', '160200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Airport of Debarkation/Airport of Embarkation', '160300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Ammunition', '160400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Band', '160500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Combat Service Support', '160600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Finance', '160700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Judge Advocate General', '160800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Labor', '160900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Laundry/Bath', '161000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Maintenance', '161100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Material', '161200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Medical', '161300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Medical Treatment Facility', '161400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Morale Welfare and Recreation', '161500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Mortuary Affairs/Graves Registration', '161600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Multiple Classes of Supply', '161700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : NATO Supply Class I', '161800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : NATO Supply Class II', '161900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : NATO Supply Class III', '162000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : NATO Supply Class IV', '162100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : NATO Supply Class V', '162200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Ordnance', '162300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Personnel Services', '162400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Petroleum Oil and Lubricants', '162500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Pipeline', '162600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Postal', '162700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Public Affairs/Public Information', '162800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Quartermaster', '162900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Railhead', '163000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Religious Support', '163100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Replacement Holding Unit', '163200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Sea Port of Debarkation/Sea Port of Embarkation', '163300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Supply', '163400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Joint Information Bureau', '163500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Transportation', '163600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class I', '163700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class II', '163800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class III', '163900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class IV', '164000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class V', '164100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class VI', '164200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class VII', '164300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class VIII', '164400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class IX', '164500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : US Supply Class X', '164600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Water', '164700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Water Purification', '164800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Sustainment : Broadcast', '164900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Naval : Naval', '170100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Named Headquarters : Allied Command Europe Rapid Reaction Corps (ARRC)', '180100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Named Headquarters : Allied Command Operations', '180200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Named Headquarters : International Security Assistance Force (ISAF)', '180300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Named Headquarters : Multinational (MN)', '180400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Emergency Operation (Land Units)', '190000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units)', '200000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : ATF DOJ', '200100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : Border Patrol', '200200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : Customs Service', '200300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : DEA', '200400', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : DOJ', '200500', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : FBI', '200600', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : Police', '200700', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : Prison', '200800', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : US Secret Service (USSS)', '200900', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : TSA', '201000', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : Coast Guard', '201100', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : US Marshals Service', '201200', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Unit : Law Enforcement (Land Units) : Internal Security Force', '201300', '10');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Unspecified', '000000', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation', '110000', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Aircraft Production/Assembly', '110100', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Ammunition and Explosives/Assembly', '110200', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Ammunition Cache', '110300', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Armament Production', '110400', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Black List Location', '110500', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Chemical-Biological-Radiological and Nuclear (CBRN)', '110600', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Engineering Equipment Production', '110700', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Engineering Equipment Production : Bridge', '110701', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Equipment Manufacture', '110800', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Government Leadership', '110900', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Gray List Location', '111000', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Mass Grave Site', '111100', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Materiel', '111200', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Mine', '111300', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Missile and Space System Production', '111400', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Nuclear (Non CBRN Defense)', '111500', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Printed Media', '111600', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Safe House', '111700', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : White List Location', '111800', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Tented Camp', '111900', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Tented Camp : Displaced Persons / Refugee / Evacuees Camp', '111901', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Tented Camp : Training Camp', '111902', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Warehouse/Storage Facility', '112000', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement', '112100', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Bureau of Alcohol-Tobacco-Firearms and Explosives (ATF) (Department of Justice)', '112101', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Border Patrol', '112102', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Customs Service', '112103', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Drug Enforcement Administration (DEA)', '112104', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Department of Justice (DOJ)', '112105', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Federal Bureau of Investigation (FBI)', '112106', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Police', '112107', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Prison', '112108', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : United States Secret Service (USSS)', '112109', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Transportation Security Administration (TSA)', '112110', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : Coast Guard', '112111', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Law Enforcement : US Marshals Service', '112112', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Emergency Operation', '112200', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Emergency Operation : Fire Station', '112201', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Installation : Emergency Operation : Emergency Medical Operation', '112202', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food', '120100', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food : Agriculture Laboratory', '120101', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food : Animal Feedlot', '120102', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food : Commercial Food Distribution Center', '120103', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food : Farm/Ranch', '120104', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food : Food Distribution', '120105', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food : Food Production Center', '120106', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food : Food Retail', '120107', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Agriculture and Food : Grain Storage', '120108', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Banking- Finance- and Insurance', '120200', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Banking- Finance- and Insurance : ATM', '120201', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Banking- Finance- and Insurance : Bank', '120202', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Banking- Finance- and Insurance : Bullion Storage', '120203', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Banking- Finance- and Insurance : Economic Infrastructure Asset', '120204', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Banking- Finance- and Insurance : Federal Reserve Bank', '120205', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Banking- Finance- and Insurance : Financial Exchange', '120206', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Banking- Finance- and Insurance : Financial Services-Other', '120207', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial', '120300', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Chemical Plant', '120301', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Firearms Manufacturer', '120302', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Firearms Retailer', '120303', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Hazardous Material Production', '120304', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Hazardous Material Storage', '120305', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Industrial Site', '120306', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Landfill', '120307', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Pharmaceutical Manufacturer', '120308', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Contaminated Hazardous Waste Site', '120309', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Commercial : Toxic Release Inventory', '120310', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Educational Facilities', '120400', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Educational Facilities : College/University', '120401', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Educational Facilities : School', '120402', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Energy Facility', '120500', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Energy Facility : Electric Power', '120501', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Energy Facility : Generation Station', '120502', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Energy Facility : Natural Gas Facility', '120503', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Energy Facility : Petroleum Facility', '120504', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Energy Facility : Petroleum/Gas/Oil', '120505', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Energy Facility : Propane Facility', '120506', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Government Site Infrastructure', '120600', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Medical : Medical', '120701', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Medical : Medical Treatment Facility (Hospital)', '120702', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Military', '120800', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Military : Military Armory', '120801', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Military : Military Base', '120802', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Postal Services', '120900', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Postal Services : Postal Distribution Center', '120901', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Postal Services : Post Office', '120902', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Public Venues', '121000', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Public Venues : Enclosed Facility', '121001', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Public Venues : Open Facility', '121002', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Public Venues : Recreational Area', '121003', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Public Venues : Religious Institution', '121004', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Special Needs', '121100', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Special Needs : Adult Day Care', '121101', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Special Needs : Child Day Care', '121102', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Special Needs : Elder Care', '121103', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Telecommunications', '121200', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Telecommunications : Broadcast Transmitter Antennae', '121201', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Telecommunications : Telecommunications', '121202', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Telecommunications : Telecommunications Tower', '121203', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation', '121300', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Airport/Air Base', '121301', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Air Traffic Control Facility', '121302', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Bus Station', '121303', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Ferry Terminal', '121304', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Helicopter Landing Site', '121305', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Maintenance Facility', '121306', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Railhead/Railroad Station', '121307', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Rest Stop', '121308', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Sea Port/Naval Base', '121309', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Ship Yard', '121310', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Toll Facility', '121311', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Traffic Inspection Facility', '121312', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Transportation : Tunnel', '121313', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply', '121400', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Control Valve', '121401', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Dam', '121402', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Discharge Outfall', '121403', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Ground Water Well', '121404', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Pumping Station', '121405', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Reservoir', '121406', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Storage Tower', '121407', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Surface Water Intake', '121408', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Wastewater Treatment Facility', '121409', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Water', '121410', '20');
INSERT INTO entity_type (name, code, symbol_set) VALUES ('Land Installation : Infrastructure : Water Supply : Water Treatment', '121411', '20');
